exclude: |
  (?x)(
      ^\.github\/|
      LICENSE$
  )

default_language_version:
  # force all unspecified python hooks to run python3
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      # Generic checks
      - id: check-case-conflict
      - id: check-symlinks
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: ^.*\.(bin|BIN)$
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        exclude: ^platformio\.ini$

  - repo: https://github.com/codespell-project/codespell
    rev: "v2.3.0"
    hooks:
      # Spell checking
      - id: codespell
        exclude: ^.*\.(svd|SVD)$

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: "v18.1.3"
    hooks:
      # C/C++ formatting
      - id: clang-format
        types_or: [c, c++]
        exclude: ^.*\/build_opt\.h$
